on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - refs/tags/*

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Diff before/after push
        env:
          GITHUB_BEFORE: ${{ github.event.before }}
          GITHUB_AFTER: ${{ github.event.after }}
        run: ls -Al && ./tests/actions-test.sh
      - name: I AM A a Tag
        run: echo "i am a tag"
        if: startsWith(github.ref, 'refs/tags')
      - name: hi
        env:
         VAR: ${{ secrets.TEST }}
        run: echo $VAR
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
